GET http://localhost:3000/ads

###
GET http://localhost:3000/ads/10

###

POST http://localhost:3000/ads
Content-Type: application/json

{
  "title": "Vélo électrique neuf",
  "description": "Vélo électrique neuf, jamais utilisé",
  "owner": "Jean@gmail.com",
  "price": 1000,
  "picture": "https://www.veloelectriquefrance.fr/wp-content/uploads/2020/06/velo-electrique-neuf.jpg",
  "location": "Paris",
  "createdAt": "2024-06-01",
  "category": { "id": 1 },
  "tags": [
    { "id": 2 }
  ]
}

###

PATCH http://localhost:3000/ads/30
Content-Type: application/json

{
    "price": 300
}

###

PUT http://localhost:3000/ads/30
Content-Type: application/json

{
  "title": "Vélo électrique neuf",
  "description": "Vélo électrique neuf, jamais utilisé",
  "owner": "Jean@gmail.com",
  "price": 1000,
  "picture": "https://www.veloelectriquefrance.fr/wp-content/uploads/2020/06/velo-electrique-neuf.jpg",
  "location": "Paris",
  "createdAt": "2024-06-01",
  "category": { "id": 1 },
  "tags": []
}

###

DELETE http://localhost:3000/ads/32