GET http://localhost:3000/categories/

###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Électronique" 
}

###

PUT http://localhost:3000/categories/6
Content-Type: application/json

{
    "name": "Immobilier"
}

###

DELETE http://localhost:3000/categories/